In [ ]:
import pandas as pd

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("GroceryStoreDataSet.csv")
print(df.head())

              MILK,BREAD,BISCUIT
0  BREAD,MILK,BISCUIT,CORNFLAKES
1            BREAD,TEA,BOURNVITA
2           JAM,MAGGI,BREAD,MILK
3              MAGGI,TEA,BISCUIT
4            BREAD,TEA,BOURNVITA

In [ ]:
transactions = df.iloc[:,0].apply(lambda x: x.split(',')).tolist()

transactions[:5]

[['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA']]

In [ ]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df_encoded = pd.DataFrame(te_array, columns=te.columns_)

df_encoded.head()

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,True,False,True,False,False,True,False,False,True,False,False
1,False,True,True,False,False,False,False,False,False,False,True
2,False,False,True,False,False,False,True,True,True,False,False
3,True,False,False,False,False,False,False,True,False,False,True
4,False,True,True,False,False,False,False,False,False,False,True

In [ ]:
frequent_itemsets = apriori(df_encoded, min_support=0.2, use_colnames=True)

frequent_itemsets

     support              itemsets
0   0.315789             (BISCUIT)
1   0.210526           (BOURNVITA)
2   0.631579               (BREAD)
3   0.421053              (COFFEE)
4   0.315789          (CORNFLAKES)
5   0.263158               (MAGGI)
6   0.210526                (MILK)
7   0.315789               (SUGER)
8   0.368421                 (TEA)
9   0.210526        (SUGER, BREAD)
10  0.210526          (TEA, BREAD)
11  0.210526  (CORNFLAKES, COFFEE)
12  0.210526       (SUGER, COFFEE)
13  0.210526          (TEA, MAGGI)

In [ ]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(SUGER),(BREAD),0.315789,0.631579,0.210526,0.666667,1.055556,1.0,0.011080,1.105263,0.076923,0.285714,0.095238,0.500000
1,(CORNFLAKES),(COFFEE),0.315789,0.421053,0.210526,0.666667,1.583333,1.0,0.077562,1.736842,0.538462,0.400000,0.424242,0.583333
2,(SUGER),(COFFEE),0.315789,0.421053,0.210526,0.666667,1.583333,1.0,0.077562,1.736842,0.538462,0.400000,0.424242,0.583333
3,(MAGGI),(TEA),0.263158,0.368421,0.210526,0.800000,2.171429,1.0,0.113573,3.157895,0.732143,0.500000,0.683333,0.685714

In [ ]:
rules[['antecedents','consequents','support','confidence','lift']]

    antecedents consequents   support  confidence      lift
0       (SUGER)     (BREAD)  0.210526    0.666667  1.055556
1  (CORNFLAKES)    (COFFEE)  0.210526    0.666667  1.583333
2       (SUGER)    (COFFEE)  0.210526    0.666667  1.583333
3       (MAGGI)       (TEA)  0.210526    0.800000  2.171429